### ISSUE TITLE
关于`FlyImage`的几个问题

### ISSUE THREAD

**Issue by zhongwuzw** [northwind/FlyImage#12]
作者你好，偶然的机会看到了你的这个开源库，看了一下你的代码，我觉得有几个问题，列出一下，欢迎交流。
1. 整体看了一下`FlyImage`库，在Example测试中，`SDWebImageTableViewCell`的实现中，对`imageView`做得操作如下，设置`masksToBounds`为`YES`会造成大量的离屏渲染，所以在`icon`测试中，会出现更加严重的掉帧。实现圆角功能应该使用你项目中实现的那种方式，使用`Core Graphics API`。
```
@implementation SDWebImageTableViewCell

- (id)imageViewWithFrame:(CGRect)frame {
	UIImageView *imageView = [[UIImageView alloc] initWithFrame:frame];
	imageView.contentMode = UIViewContentModeScaleAspectFill;
	imageView.layer.masksToBounds = YES;  //会触发离屏渲染，导致滑动时掉帧严重
	imageView.layer.cornerRadius = 10;
	[self addSubview:imageView];
	
	return imageView;
}
```

2. 在进行图片下载时，给`Session`的配置为`backgroundSessionConfigurationWithIdentifier`，即后台模式，所以在进行下载时，其优先级比较低，也就对性能消耗比`defaultSessionConfiguration`要低一些，其下载完成时间会变长。

3. 下载时使用了[AFNetworking](https://github.com/AFNetworking/AFNetworking) 的`SessionManager`进行下载，所以当不再需要`Session`时，需要调用`invalidateAndCancel`或`finishTasksAndInvalidate `(`AFURLSessionManager`提供了封装好的`- (void)invalidateSessionCancelingTasks:(BOOL)cancelPendingTasks`方法)，否则会造成内存泄露，因为`Session`会强引用`delegate`。[Apple Developer Documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/NSURLSessionConcepts/NSURLSessionConcepts.html)
> Important: The session object keeps a strong reference to the delegate until your app explicitly invalidates the session. If you do not invalidate the session, your app leaks memory.

4. 有不对的地方欢迎指正。

**Comment by northwind** [comment]
@zhongwuzw 多谢指正，欢迎提交pr

**Comment by LiuHuanQing** [comment]
我也补充一个
`_blocks`是线程不安全的

```objc
- (void)executeWithImage:(UIImage*)image
{
    for (FlyImageCacheRetrieveBlock block in _blocks) {
        block(self.name, image);
    }
    [_blocks removeAllObjects];
}
```

**Comment by northwind** [comment]
@zhongwuzw 
`masksToBounds` 是特意增加的，为了模拟圆角的情况。

**Comment by northwind** [comment]
https://github.com/northwind/FlyImage/pull/15

**Comment by zhongwuzw** [comment]
@northwind ，嗯，我知道是进行圆角，这种方式会导致离屏渲染，所以要使用`Core Graphics API`直接将`image`处理成圆角，`imageView`就不用设置`masksToBounds`了。就用你自己库示例使用的方法，你的这个`FlyImageTableViewCell`文件中就没有调用`masksToBounds`方法。
