### ISSUE TITLE
FlyImage_WebP宏错误导致webp编译不过

### ISSUE THREAD

**Issue by LiuHuanQing** [northwind/FlyImage#13]
1.FlyImage.podspec 中使用的是**FLYIMAGE_WEBP**代码中使用的是**FlyImage_WebP**
2.podfile中使用use_frameworks!
会找不到**libwebp/webp/decode.h**

<code>
#ifdef FLYIMAGE_WEBP
#import "libwebp/webp/decode.h"
#endif
</code>

**Comment by YyItRoad** [comment]
是的，我也遇到了

**Comment by northwind** [comment]
@LiuHuanQing @YyItRoad 已经fix了`FlyImage_WebP`的bug，再试试

https://github.com/northwind/FlyImage/pull/14
