### ISSUE TITLE
如果是单张 大图,分辨率非常高的情况下.

### ISSUE THREAD

**Issue by ghost** [northwind/FlyImage#18]
就比如,我有一个分辨率极高的图,要在pad 上渲染.现在的情况是,内存直接暴增,直接crash. 这个库是否可以完美解决?减少内存的开销?
我是不是可以这么理解.比如,普通加载一张图,需要的是500M ,如果使用这个库的话,内存也就只需要250M.当然,我现在还没进行试验.

**Comment by northwind** [comment]
@andywangzhen 这个库主要提升多张小图同时渲染的效率，大图会内存暴增，不建议你使用。
