### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by LeoCai92** [northwind/FlyImage#9]
编译提示错误：
FlyImage/src/MoneyKeeper/MoneyKeeper/FlyImage/Core/FlyImageDownloader.m:229:50: Sending 'void (^)(NSProgress \* _Nonnull __strong)' to parameter of incompatible type 'NSProgress *__autoreleasing  _Nullable \* _Nullable'

**Comment by northwind** [comment]
@LeoCai92 Xcode版本号和 iOS版本号都是多少？

**Comment by LeoCai92** [comment]
@northwind Xocde8.0和iOS10（模拟器）
当时是为了测试这个框架的图片下载加载的性能，结果在调用图片下载函数，遇到参数类型不匹配。。。是不是你的这个框架用到的AFNetworking版本有要求呢？我用的AFNetworking版本是2.6.3

**Comment by northwind** [comment]
是的，依赖最新的`AFNetworking`版本号大于3.1

**Comment by LeoCai92** [comment]
@northwind 原来如此，我试试看，3Q

**Comment by LeoCai92** [comment]
@northwind 建议阔以在你的框架中集成AFN

**Comment by northwind** [comment]
@LeoCai92 暂时还没有考虑，AFN非常成熟，默认大家都会集成
